# Generated by Django 6.0.8 on 2026-08-05 19:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manyumbu10', '0003_comment_hashtag_post_notification_hiddenpost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caption', models.TextField(blank=True, max_length=2200)),
                ('audience', models.CharField(choices=[('public', 'Public'), ('followers', 'Followers'), ('close_friends', 'Close friends'), ('selected', 'Selected users'), ('only_me', 'Only me')], default='public', max_length=20)),
                ('comments_enabled', models.BooleanField(default=True)),
                ('status', models.CharField(default='published', max_length=20)),
                ('location_name', models.CharField(blank=True, max_length=140)),
                ('video', models.FileField(blank=True, null=True, upload_to='reels/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='reel-covers/')),
                ('video_url', models.URLField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('aspect_ratio', models.CharField(blank=True, max_length=20)),
                ('processing_status', models.CharField(default='pending', max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HiddenReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_reels', to=settings.AUTH_USER_MODEL)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by', to='manyumbu10.reel')),
            ],
        ),
        migrations.CreateModel(
            name='ReelAudienceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_audience', to='manyumbu10.reel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_reels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReelComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=1000)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='manyumbu10.reelcomment')),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='manyumbu10.reel')),
            ],
        ),
        migrations.CreateModel(
            name='ReelHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_links', to='manyumbu10.hashtag')),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='manyumbu10.reel')),
            ],
        ),
        migrations.CreateModel(
            name='ReelLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='manyumbu10.reel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReelMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='manyumbu10.reel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_mentions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReelNotInterested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_interested_by', to='manyumbu10.reel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_interested_reels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReelReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate', 'Hate or abusive content'), ('nudity', 'Nudity or sexual content'), ('violence', 'Violence'), ('scam', 'Scam or fraud'), ('false_information', 'False information'), ('intellectual_property', 'Intellectual property'), ('other', 'Other')], max_length=40)),
                ('details', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='manyumbu10.reel')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReelTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_users', to='manyumbu10.reel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_reels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReelView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_duration', models.FloatField(default=0)),
                ('completion_percentage', models.FloatField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('replay_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='manyumbu10.reel')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='manyumbu10.reel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('story_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], default='text', max_length=20)),
                ('caption', models.TextField(blank=True, max_length=1000)),
                ('audience', models.CharField(choices=[('everyone', 'Everyone'), ('followers', 'Followers'), ('close_friends', 'Close friends'), ('selected', 'Selected users'), ('hide_selected', 'Hide selected users')], default='everyone', max_length=20)),
                ('background_style', models.CharField(blank=True, max_length=120)),
                ('link_url', models.URLField(blank=True)),
                ('location_name', models.CharField(blank=True, max_length=140)),
                ('sticker_metadata', models.JSONField(blank=True, default=dict)),
                ('replies_enabled', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('expired', 'Expired'), ('deleted', 'Deleted'), ('removed', 'Removed')], default='published', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoryAudienceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_audience', to='manyumbu10.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_stories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoryHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_links', to='manyumbu10.hashtag')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='manyumbu10.story')),
            ],
        ),
        migrations.CreateModel(
            name='StoryHiddenUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_users', to='manyumbu10.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_from_stories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoryHighlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='highlight-covers/')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_highlights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoryHighlightItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='manyumbu10.storyhighlight')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_items', to='manyumbu10.story')),
            ],
        ),
        migrations.CreateModel(
            name='StoryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='stories/')),
                ('media_type', models.CharField(max_length=20)),
                ('media_url', models.URLField(blank=True)),
                ('secure_url', models.URLField(blank=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='story-thumbnails/')),
                ('upload_provider_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='manyumbu10.story')),
            ],
        ),
        migrations.CreateModel(
            name='StoryMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='manyumbu10.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_mentions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoryPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=180)),
                ('show_results', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='manyumbu10.story')),
            ],
        ),
        migrations.CreateModel(
            name='StoryPollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=80)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='manyumbu10.storypoll')),
            ],
        ),
        migrations.CreateModel(
            name='StoryPollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='manyumbu10.storypolloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='manyumbu10.storypoll')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoryReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('laugh', 'Laugh'), ('surprise', 'Surprise'), ('sad', 'Sad'), ('fire', 'Fire'), ('celebration', 'Celebration')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='manyumbu10.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoryReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_replies', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='manyumbu10.story')),
            ],
        ),
        migrations.CreateModel(
            name='StoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate', 'Hate or abusive content'), ('nudity', 'Nudity or sexual content'), ('violence', 'Violence'), ('scam', 'Scam or fraud'), ('false_information', 'False information'), ('intellectual_property', 'Intellectual property'), ('other', 'Other')], max_length=40)),
                ('details', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_reports', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='manyumbu10.story')),
            ],
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='manyumbu10.story')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['author', 'status', 'published_at'], name='manyumbu10__author__c7c4e6_idx'),
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['audience', 'status', 'published_at'], name='manyumbu10__audienc_6f1539_idx'),
        ),
        migrations.AddConstraint(
            model_name='hiddenreel',
            constraint=models.UniqueConstraint(fields=('reel', 'user'), name='unique_hidden_reel'),
        ),
        migrations.AddConstraint(
            model_name='reelaudienceuser',
            constraint=models.UniqueConstraint(fields=('reel', 'user'), name='unique_reel_audience_user'),
        ),
        migrations.AddConstraint(
            model_name='reelhashtag',
            constraint=models.UniqueConstraint(fields=('reel', 'hashtag'), name='unique_reel_hashtag'),
        ),
        migrations.AddConstraint(
            model_name='reellike',
            constraint=models.UniqueConstraint(fields=('reel', 'user'), name='unique_reel_like'),
        ),
        migrations.AddConstraint(
            model_name='reelmention',
            constraint=models.UniqueConstraint(fields=('reel', 'user'), name='unique_reel_mention'),
        ),
        migrations.AddConstraint(
            model_name='reelnotinterested',
            constraint=models.UniqueConstraint(fields=('reel', 'user'), name='unique_reel_not_interested'),
        ),
        migrations.AddConstraint(
            model_name='reelreport',
            constraint=models.UniqueConstraint(fields=('reel', 'reporter', 'reason'), name='unique_reel_report_reason'),
        ),
        migrations.AddConstraint(
            model_name='reeltag',
            constraint=models.UniqueConstraint(fields=('reel', 'user'), name='unique_reel_tag'),
        ),
        migrations.AddConstraint(
            model_name='reelview',
            constraint=models.UniqueConstraint(fields=('reel', 'viewer'), name='unique_reel_view'),
        ),
        migrations.AddConstraint(
            model_name='savedreel',
            constraint=models.UniqueConstraint(fields=('reel', 'user'), name='unique_saved_reel'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['author', 'status', 'expires_at'], name='manyumbu10__author__aaf864_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['audience', 'status', 'expires_at'], name='manyumbu10__audienc_245909_idx'),
        ),
        migrations.AddConstraint(
            model_name='storyaudienceuser',
            constraint=models.UniqueConstraint(fields=('story', 'user'), name='unique_story_audience_user'),
        ),
        migrations.AddConstraint(
            model_name='storyhashtag',
            constraint=models.UniqueConstraint(fields=('story', 'hashtag'), name='unique_story_hashtag'),
        ),
        migrations.AddConstraint(
            model_name='storyhiddenuser',
            constraint=models.UniqueConstraint(fields=('story', 'user'), name='unique_story_hidden_user'),
        ),
        migrations.AddIndex(
            model_name='storyhighlight',
            index=models.Index(fields=['owner', 'display_order'], name='manyumbu10__owner_i_1ccd0a_idx'),
        ),
        migrations.AddConstraint(
            model_name='storyhighlightitem',
            constraint=models.UniqueConstraint(fields=('highlight', 'story'), name='unique_highlight_story'),
        ),
        migrations.AddConstraint(
            model_name='storymention',
            constraint=models.UniqueConstraint(fields=('story', 'user'), name='unique_story_mention'),
        ),
        migrations.AddConstraint(
            model_name='storypolloption',
            constraint=models.UniqueConstraint(fields=('poll', 'display_order'), name='unique_story_poll_option_order'),
        ),
        migrations.AddConstraint(
            model_name='storypollvote',
            constraint=models.UniqueConstraint(fields=('poll', 'voter'), name='unique_story_poll_vote'),
        ),
        migrations.AddConstraint(
            model_name='storyreaction',
            constraint=models.UniqueConstraint(fields=('story', 'user'), name='unique_story_reaction'),
        ),
        migrations.AddConstraint(
            model_name='storyreport',
            constraint=models.UniqueConstraint(fields=('story', 'reporter', 'reason'), name='unique_story_report_reason'),
        ),
        migrations.AddIndex(
            model_name='storyview',
            index=models.Index(fields=['story', 'created_at'], name='manyumbu10__story_i_67f989_idx'),
        ),
        migrations.AddConstraint(
            model_name='storyview',
            constraint=models.UniqueConstraint(fields=('story', 'viewer'), name='unique_story_view'),
        ),
    ]
