# Generated by Django 6.0.8 on 2026-08-05 20:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manyumbu10', '0004_reel_hiddenreel_reelaudienceuser_reelcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_type', models.CharField(choices=[('private', 'Private')], default='private', max_length=20)),
                ('private_pair_key', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('soft_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprivacysettings',
            name='allow_forwarded_messages_from_unknown_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprivacysettings',
            name='allow_message_requests',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprivacysettings',
            name='send_read_receipts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprivacysettings',
            name='show_last_seen',
            field=models.CharField(default='people_i_follow', max_length=30),
        ),
        migrations.AddField(
            model_name='userprivacysettings',
            name='show_online_status',
            field=models.CharField(default='everyone', max_length=30),
        ),
        migrations.AddField(
            model_name='userprivacysettings',
            name='show_recording_indicator',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprivacysettings',
            name='show_typing_indicator',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprivacysettings',
            name='who_can_add_to_conversations',
            field=models.CharField(default='people_i_follow', max_length=30),
        ),
        migrations.AddField(
            model_name='userprivacysettings',
            name='who_can_message_me',
            field=models.CharField(default='everyone', max_length=30),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio'), ('voice_note', 'Voice note'), ('location', 'Location'), ('contact', 'Contact'), ('post_share', 'Post share'), ('reel_share', 'Reel share'), ('story_reply', 'Story reply'), ('system', 'System')], default='text', max_length=30)),
                ('text', models.TextField(blank=True, max_length=5000)),
                ('forwarded_from', models.JSONField(blank=True, default=dict)),
                ('shared_content', models.JSONField(blank=True, default=dict)),
                ('location_payload', models.JSONField(blank=True, default=dict)),
                ('contact_payload', models.JSONField(blank=True, default=dict)),
                ('client_message_id', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('is_forwarded', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_for_everyone_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='manyumbu10.conversation')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='manyumbu10.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('marked_unread', models.BooleanField(default=False)),
                ('cleared_before', models.DateTimeField(blank=True, null=True)),
                ('request_state', models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('deleted', 'Deleted'), ('spam', 'Spam')], default='none', max_length=20)),
                ('notification_preference', models.CharField(default='all', max_length=20)),
                ('keep_archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='manyumbu10.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_participations', to=settings.AUTH_USER_MODEL)),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_read_by', to='manyumbu10.message')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_for_conversations', to='manyumbu10.message'),
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='messages/')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio'), ('voice_note', 'Voice note')], max_length=30)),
                ('file_name', models.CharField(max_length=180)),
                ('mime_type', models.CharField(max_length=120)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='message-thumbnails/')),
                ('waveform', models.JSONField(blank=True, default=list)),
                ('processing_status', models.CharField(default='ready', max_length=20)),
                ('malware_scan_status', models.CharField(default='pending', max_length=20)),
                ('upload_provider_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='manyumbu10.message')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_attachments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_for', to='manyumbu10.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_deletions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageDeliveryReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(blank=True, max_length=120)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_receipts', to='manyumbu10.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_delivery_receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessagePin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='manyumbu10.conversation')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='manyumbu10.message')),
                ('pinned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_pins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('laugh', 'Laugh'), ('surprise', 'Surprise'), ('sad', 'Sad'), ('celebration', 'Celebration')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='manyumbu10.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='manyumbu10.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_read_receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate', 'Hate or abusive content'), ('nudity', 'Nudity or sexual content'), ('violence', 'Violence'), ('scam', 'Scam or fraud'), ('false_information', 'False information'), ('intellectual_property', 'Intellectual property'), ('other', 'Other')], max_length=40)),
                ('details', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='manyumbu10.message')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preview_text', models.CharField(blank=True, max_length=280)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('deleted', 'Deleted'), ('spam', 'Spam')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('spam_score', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_request', to='manyumbu10.conversation')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_message_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_message_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='manyumbu10.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_stars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=120)),
                ('device_name', models.CharField(blank=True, max_length=120)),
                ('platform', models.CharField(blank=True, max_length=40)),
                ('push_token', models.CharField(blank=True, max_length=255)),
                ('notification_preferences', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('recently_active', 'Recently active')], default='offline', max_length=30)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebSocketSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=255)),
                ('device_id', models.CharField(blank=True, max_length=120)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websocket_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_records', to='manyumbu10.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_archives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('conversation', 'user'), name='unique_conversation_archive')],
            },
        ),
        migrations.CreateModel(
            name='ConversationClearState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleared_before', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clear_states', to='manyumbu10.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_clear_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('conversation', 'user'), name='unique_conversation_clear_state')],
            },
        ),
        migrations.CreateModel(
            name='ConversationMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mute_records', to='manyumbu10.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_mutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('conversation', 'user'), name='unique_conversation_mute')],
            },
        ),
        migrations.CreateModel(
            name='ConversationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate', 'Hate or abusive content'), ('nudity', 'Nudity or sexual content'), ('violence', 'Violence'), ('scam', 'Scam or fraud'), ('false_information', 'False information'), ('intellectual_property', 'Intellectual property'), ('other', 'Other')], max_length=40)),
                ('details', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='manyumbu10.conversation')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='manyumbu10__status_9d4fd6_idx')],
                'constraints': [models.UniqueConstraint(fields=('conversation', 'reporter', 'reason'), name='unique_conversation_report_reason')],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='manyumbu10__convers_5fecb9_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='manyumbu10__sender__d05280_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type', 'created_at'], name='manyumbu10__message_535f43_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_message_id', ''), _negated=True), fields=('sender', 'client_message_id'), name='unique_message_client_id_per_sender'),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['user', 'archived_at', 'updated_at'], name='manyumbu10__user_id_82f537_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['conversation', 'request_state'], name='manyumbu10__convers_416494_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationparticipant',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='unique_conversation_participant'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['conversation_type', 'last_message_at'], name='manyumbu10__convers_e0079c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status', 'updated_at'], name='manyumbu10__status_befc46_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['message', 'kind'], name='manyumbu10__message_46b81a_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['owner', 'created_at'], name='manyumbu10__owner_i_424bfa_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagedeletion',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='unique_message_delete_for_user'),
        ),
        migrations.AddConstraint(
            model_name='messagedeliveryreceipt',
            constraint=models.UniqueConstraint(fields=('message', 'user', 'device_id'), name='unique_message_delivery_receipt'),
        ),
        migrations.AddIndex(
            model_name='messagepin',
            index=models.Index(fields=['conversation', 'created_at'], name='manyumbu10__convers_a0cef9_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagepin',
            constraint=models.UniqueConstraint(fields=('message', 'conversation'), name='unique_conversation_message_pin'),
        ),
        migrations.AddConstraint(
            model_name='messagereaction',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='unique_message_reaction'),
        ),
        migrations.AddIndex(
            model_name='messagereadreceipt',
            index=models.Index(fields=['user', 'read_at'], name='manyumbu10__user_id_af800b_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagereadreceipt',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='unique_message_read_receipt'),
        ),
        migrations.AddIndex(
            model_name='messagereport',
            index=models.Index(fields=['status', 'created_at'], name='manyumbu10__status_c39f92_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagereport',
            constraint=models.UniqueConstraint(fields=('message', 'reporter', 'reason'), name='unique_message_report_reason'),
        ),
        migrations.AddIndex(
            model_name='messagerequest',
            index=models.Index(fields=['receiver', 'status', 'created_at'], name='manyumbu10__receive_f1f262_idx'),
        ),
        migrations.AddIndex(
            model_name='messagerequest',
            index=models.Index(fields=['sender', 'receiver'], name='manyumbu10__sender__1313de_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagerequest',
            constraint=models.UniqueConstraint(fields=('sender', 'receiver', 'status'), name='unique_message_request_state'),
        ),
        migrations.AddIndex(
            model_name='messagestar',
            index=models.Index(fields=['user', 'created_at'], name='manyumbu10__user_id_9f95a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagestar',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='unique_message_star'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user', 'revoked_at'], name='manyumbu10__user_id_b79392_idx'),
        ),
        migrations.AddConstraint(
            model_name='userdevice',
            constraint=models.UniqueConstraint(fields=('user', 'device_id'), name='unique_user_device'),
        ),
        migrations.AddIndex(
            model_name='websocketsession',
            index=models.Index(fields=['user', 'disconnected_at'], name='manyumbu10__user_id_d0462c_idx'),
        ),
        migrations.AddIndex(
            model_name='websocketsession',
            index=models.Index(fields=['channel_name'], name='manyumbu10__channel_4e0e48_idx'),
        ),
    ]
