services:
  - type: web
    name: manyumbu-api
    env: docker
    plan: free
    healthCheckPath: /health/ready/
    envVars:
      - key: MANYUMBU_ENV
        value: production

      - key: DJANGO_DEBUG
        value: "0"

      - key: DATABASE_URL
        sync: false

      - key: REDIS_URL
        fromService:
          type: redis
          name: manyumbu-redis
          property: connectionString

  - type: redis
    name: manyumbu-redis
    plan: free
    ipAllowList: []