import { useMutation, useQuery } from "@tanstack/react-query";
import { router } from "expo-router";
import { useState } from "react";
import { FlatList, Pressable, Text, TextInput, View } from "react-native";
import { createVerificationRequest, listVerificationRequests } from "../../src/api/phase7";
import { validateVerification } from "../../src/calls/validation";

export default function VerificationScreen() {
  const [reason, setReason] = useState(""); const [link, setLink] = useState(""); const [type, setType] = useState<"creator" | "business">("creator");
  const requests = useQuery({ queryKey: ["verification-requests"], queryFn: listVerificationRequests });
  const submit = useMutation({ mutationFn: () => { const links = link ? [link] : []; const error = validateVerification(reason, links); if (error) throw new Error(error); return createVerificationRequest({ account_type: type, public_name: "Manyumbu profile", category: type, reason, supporting_links: links }); }, onSuccess: () => { setReason(""); requests.refetch(); } });
  return <View style={{ flex: 1, backgroundColor: "#FFFFFF", paddingTop: 48, paddingHorizontal: 18 }}><Pressable onPress={() => router.back()}><Text style={{ color: "#126C57", fontWeight: "900" }}>Back</Text></Pressable><Text style={{ fontSize: 26, fontWeight: "900", marginTop: 16 }}>Verification</Text><View style={{ flexDirection: "row", gap: 8, marginTop: 12 }}>{(["creator", "business"] as const).map((item) => <Pressable key={item} onPress={() => setType(item)} style={{ borderWidth: 1, borderColor: type === item ? "#126C57" : "#D1D5DB", padding: 10, borderRadius: 8 }}><Text style={{ color: type === item ? "#126C57" : "#111827", fontWeight: "800" }}>{item}</Text></Pressable>)}</View><TextInput value={reason} onChangeText={setReason} placeholder="Reason for verification" multiline style={{ minHeight: 100, borderWidth: 1, borderColor: "#D1D5DB", borderRadius: 8, padding: 12, marginTop: 12 }} /><TextInput value={link} onChangeText={setLink} autoCapitalize="none" placeholder="Supporting link" style={{ borderWidth: 1, borderColor: "#D1D5DB", borderRadius: 8, padding: 12, marginTop: 12 }} /><Pressable onPress={() => submit.mutate()} style={{ backgroundColor: "#126C57", padding: 14, borderRadius: 8, marginTop: 16, alignItems: "center" }}><Text style={{ color: "white", fontWeight: "900" }}>Submit</Text></Pressable>{submit.isError ? <Text style={{ color: "#B91C1C", marginTop: 10 }}>{submit.error.message}</Text> : null}<FlatList data={requests.data?.data.results ?? []} keyExtractor={(item) => item.id} renderItem={({ item }) => <View style={{ paddingVertical: 10, borderBottomWidth: 1, borderColor: "#E5E7EB" }}><Text style={{ fontWeight: "800" }}>{item.public_name}</Text><Text style={{ color: "#6B7280" }}>{item.status} · {item.account_type}</Text></View>} /></View>;
}
