import { api } from "./client";
import { getTokenItem } from "../store/tokenStorage";
import type { ApiResponse } from "../types/auth";
import type { Paginated } from "../types/profile";
import type { AppNotification, Group, GroupInvitation, GroupMember, GroupMessage, GroupMessagePage, GroupPage, JoinRequest, NotificationPreferences } from "../types/groups";
import type { AttachmentUpload } from "./messaging";

async function authHeader() { const token = await getTokenItem("manyumbu_access"); return token ? { Authorization: `Bearer ${token}` } : {}; }
export async function getGroupWsToken() { return getTokenItem("manyumbu_access"); }
export async function listGroups(params: { q?: string; archived?: boolean; type?: "public" } = {}) { const { data } = await api.get<ApiResponse<GroupPage>>("/groups/", { params: { q: params.q, archived: params.archived ? "1" : undefined, type: params.type }, headers: await authHeader() }); return data; }
export async function createGroup(payload: { name: string; description?: string; privacy?: string; members?: string[] }) { const { data } = await api.post<ApiResponse<{ group: Group }>>("/groups/", payload, { headers: await authHeader() }); return data; }
export async function getGroup(id: string) { const { data } = await api.get<ApiResponse<{ group: Group }>>(`/groups/${id}/`, { headers: await authHeader() }); return data; }
export async function updateGroup(id: string, payload: Partial<Group>) { const { data } = await api.patch<ApiResponse<{ group: Group }>>(`/groups/${id}/`, payload, { headers: await authHeader() }); return data; }
export async function listGroupMembers(id: string) { const { data } = await api.get<ApiResponse<Paginated<GroupMember>>>(`/groups/${id}/members/`, { headers: await authHeader() }); return data; }
export async function addGroupMembers(id: string, members: string[]) { const { data } = await api.post<ApiResponse<{ members: GroupMember[] }>>(`/groups/${id}/members/`, { members }, { headers: await authHeader() }); return data; }
export async function removeGroupMember(id: string, username: string) { const { data } = await api.delete<ApiResponse<Record<string, never>>>(`/groups/${id}/members/${username}/`, { headers: await authHeader() }); return data; }
export async function updateGroupMemberRole(id: string, username: string, role: "admin" | "moderator" | "member") { return groupAction(id, "roles", { username, role }); }
export async function groupAction(id: string, action: "leave" | "archive" | "unarchive" | "mute" | "clear" | "report" | "roles" | "ban" | "restrict" | "transfer-ownership", payload: Record<string, unknown> = {}) { const { data } = await api.post<ApiResponse<{ group?: Group; report_id?: number }>>(`/groups/${id}/${action}/`, payload, { headers: await authHeader() }); return data; }
export async function listGroupMessages(id: string, params: { before?: string; after?: string } = {}) { const { data } = await api.get<ApiResponse<GroupMessagePage>>(`/groups/${id}/messages/`, { params, headers: await authHeader() }); return data; }
export async function sendGroupTextMessage(id: string, text: string, clientMessageId: string, replyToId?: string) { const { data } = await api.post<ApiResponse<{ message: GroupMessage; deduplicated: boolean }>>(`/groups/${id}/messages/`, { message_type: "text", text, client_message_id: clientMessageId, reply_to_id: replyToId }, { headers: await authHeader() }); return data; }
export async function sendGroupAttachmentMessage(id: string, text: string, upload: AttachmentUpload, onProgress?: (progress: number) => void) { const form = new FormData(); form.append("message_type", upload.kind); form.append("attachment_kind", upload.kind); form.append("text", text); if (upload.duration) form.append("duration", String(upload.duration)); if (upload.width) form.append("width", String(upload.width)); if (upload.height) form.append("height", String(upload.height)); if (upload.clientMessageId) form.append("client_message_id", upload.clientMessageId); if (upload.replyToId) form.append("reply_to_id", upload.replyToId); form.append("attachments", upload as unknown as Blob); const { data } = await api.post<ApiResponse<{ message: GroupMessage; deduplicated: boolean }>>(`/groups/${id}/messages/`, form, { headers: { ...(await authHeader()), "Content-Type": "multipart/form-data" }, onUploadProgress: (event) => event.total && onProgress?.(Math.round((event.loaded / event.total) * 100)) }); return data; }
export async function groupMessageAction(id: string, action: "react" | "star" | "pin" | "delivered" | "read" | "report" | "forward", payload: Record<string, unknown> = {}) { const { data } = await api.post<ApiResponse<{ message?: GroupMessage; report_id?: number }>>(`/group-messages/${id}/${action}/`, payload, { headers: await authHeader() }); return data; }
export async function removeGroupMessageAction(id: string, action: "react" | "star" | "pin" | "for-me" | "for-everyone") { const { data } = await api.delete<ApiResponse<{ message?: GroupMessage }>>(`/group-messages/${id}/${action}/`, { headers: await authHeader() }); return data; }
export async function searchGroupMessages(id: string, q: string) { const { data } = await api.get<ApiResponse<Paginated<GroupMessage>>>(`/groups/${id}/search/`, { params: { q }, headers: await authHeader() }); return data; }
export async function listGroupMedia(id: string) { const { data } = await api.get<ApiResponse<Paginated<{ message_id: string; kind: string; file_name: string; url: string; file_size: number }>>>(`/groups/${id}/media/`, { headers: await authHeader() }); return data; }
export async function listGroupInvitations(id: string) { const { data } = await api.get<ApiResponse<Paginated<GroupInvitation>>>(`/groups/${id}/invitations/`, { headers: await authHeader() }); return data; }
export async function createGroupInvitation(id: string, expiresHours = 24) { const { data } = await api.post<ApiResponse<{ invitation_id: string; token: string; expires_at: string | null }>>(`/groups/${id}/invitations/`, { expires_hours: expiresHours }, { headers: await authHeader() }); return data; }
export async function joinGroupByInvitation(token: string) { const { data } = await api.post<ApiResponse<{ group: Group; joined: boolean; request_id: string }>>(`/group-invitations/${token}/join/`, {}, { headers: await authHeader() }); return data; }
export async function listJoinRequests(id: string) { const { data } = await api.get<ApiResponse<Paginated<JoinRequest>>>(`/groups/${id}/join-requests/`, { headers: await authHeader() }); return data; }
export async function decideJoinRequest(groupId: string, requestId: string, action: "approve" | "reject") { const { data } = await api.post<ApiResponse<{ status: string }>>(`/groups/${groupId}/join-requests/${requestId}/${action}/`, {}, { headers: await authHeader() }); return data; }
export async function listNotifications() { const { data } = await api.get<ApiResponse<Paginated<AppNotification>>>("/notifications/", { headers: await authHeader() }); return data; }
export async function notificationAction(id: string, action: "read" | "seen") { const { data } = await api.post<ApiResponse<Record<string, never>>>(`/notifications/${id}/${action}/`, {}, { headers: await authHeader() }); return data; }
export async function markAllNotificationsRead() { const { data } = await api.post<ApiResponse<Record<string, never>>>("/notifications/read-all/", {}, { headers: await authHeader() }); return data; }
export async function getNotificationPreferences() { const { data } = await api.get<ApiResponse<{ preferences: NotificationPreferences }>>("/notification-preferences/", { headers: await authHeader() }); return data; }
export async function updateNotificationPreferences(payload: Partial<NotificationPreferences>) { const { data } = await api.patch<ApiResponse<{ preferences: NotificationPreferences }>>("/notification-preferences/", payload, { headers: await authHeader() }); return data; }
