import { api } from "./client";
import { getTokenItem } from "../store/tokenStorage";
import type { ApiResponse } from "../types/auth";
import type { ChatMessage, Conversation, CursorPage, MessageRequest } from "../types/messaging";
import type { Paginated } from "../types/profile";

async function authHeader() {
  const token = await getTokenItem("manyumbu_access");
  return token ? { Authorization: `Bearer ${token}` } : {};
}

export async function getWsToken() { return getTokenItem("manyumbu_access"); }
export async function listConversations(params: { cursor?: string | null; archived?: boolean; q?: string } = {}) { const { data } = await api.get<ApiResponse<CursorPage<Conversation>>>("/conversations/", { params: { cursor: params.cursor, archived: params.archived ? "1" : undefined, q: params.q }, headers: await authHeader() }); return data; }
export async function startConversation(username: string, initial_text = "") { const { data } = await api.post<ApiResponse<{ conversation: Conversation; created: boolean; message_request_required: boolean }>>("/conversations/", { username, initial_text }, { headers: await authHeader() }); return data; }
export async function getConversation(id: string) { const { data } = await api.get<ApiResponse<{ conversation: Conversation }>>(`/conversations/${id}/`, { headers: await authHeader() }); return data; }
export async function listMessages(conversationId: string, params: { before?: string | null; after?: string | null } = {}) { const { data } = await api.get<ApiResponse<CursorPage<ChatMessage>>>(`/conversations/${conversationId}/messages/`, { params, headers: await authHeader() }); return data; }
export async function sendTextMessage(conversationId: string, text: string, clientMessageId: string, replyToId?: string) { const { data } = await api.post<ApiResponse<{ message: ChatMessage; deduplicated: boolean }>>(`/conversations/${conversationId}/messages/`, { message_type: "text", text, client_message_id: clientMessageId, reply_to_id: replyToId }, { headers: await authHeader() }); return data; }
export type AttachmentUpload = { uri: string; name: string; type: string; kind: string; duration?: number; width?: number; height?: number };
export async function sendAttachmentMessage(conversationId: string, text: string, upload: AttachmentUpload, onProgress?: (progress: number) => void) { const form = new FormData(); form.append("message_type", upload.kind); form.append("attachment_kind", upload.kind); form.append("text", text); if (upload.duration) form.append("duration", String(upload.duration)); if (upload.width) form.append("width", String(upload.width)); if (upload.height) form.append("height", String(upload.height)); form.append("attachments", upload as unknown as Blob); const { data } = await api.post<ApiResponse<{ message: ChatMessage; deduplicated: boolean }>>(`/conversations/${conversationId}/messages/`, form, { headers: { ...(await authHeader()), "Content-Type": "multipart/form-data" }, onUploadProgress: (event) => event.total && onProgress?.(Math.round((event.loaded / event.total) * 100)) }); return data; }
export async function updateMessage(messageId: string, text: string) { const { data } = await api.patch<ApiResponse<{ message: ChatMessage }>>(`/messages/${messageId}/`, { text }, { headers: await authHeader() }); return data; }
export async function deleteMessageForMe(messageId: string) { const { data } = await api.delete<ApiResponse<Record<string, never>>>(`/messages/${messageId}/for-me/`, { headers: await authHeader() }); return data; }
export async function deleteMessageForEveryone(messageId: string) { const { data } = await api.delete<ApiResponse<{ message: ChatMessage }>>(`/messages/${messageId}/for-everyone/`, { headers: await authHeader() }); return data; }
export async function messageAction(messageId: string, action: "react" | "star" | "pin" | "delivered" | "read" | "report", payload: Record<string, unknown> = {}) { const { data } = await api.post<ApiResponse<{ message?: ChatMessage; report_id?: number }>>(`/messages/${messageId}/${action}/`, payload, { headers: await authHeader() }); return data; }
export async function removeMessageAction(messageId: string, action: "react" | "star" | "pin") { const { data } = await api.delete<ApiResponse<{ message: ChatMessage }>>(`/messages/${messageId}/${action}/`, { headers: await authHeader() }); return data; }
export async function forwardMessage(messageId: string, username: string, note = "") { const { data } = await api.post<ApiResponse<{ message: ChatMessage; conversation: Conversation }>>(`/messages/${messageId}/forward/`, { username, note }, { headers: await authHeader() }); return data; }
export async function conversationAction(conversationId: string, action: "read" | "unread" | "archive" | "unarchive" | "mute" | "clear" | "report", payload: Record<string, unknown> = {}) { const { data } = await api.post<ApiResponse<{ conversation?: Conversation; report_id?: number }>>(`/conversations/${conversationId}/${action}/`, payload, { headers: await authHeader() }); return data; }
export async function unmuteConversation(conversationId: string) { const { data } = await api.delete<ApiResponse<{ conversation: Conversation }>>(`/conversations/${conversationId}/mute/`, { headers: await authHeader() }); return data; }
export async function searchMessages(conversationId: string, q: string) { const { data } = await api.get<ApiResponse<Paginated<ChatMessage>>>(`/conversations/${conversationId}/search/`, { params: { q }, headers: await authHeader() }); return data; }
export async function sharedMedia(conversationId: string, kind?: string) { const { data } = await api.get<ApiResponse<Paginated<{ message_id: string; attachment: unknown }>>>(`/conversations/${conversationId}/media/`, { params: { kind }, headers: await authHeader() }); return data; }
export async function listMessageRequests() { const { data } = await api.get<ApiResponse<Paginated<MessageRequest>>>("/message-requests/", { headers: await authHeader() }); return data; }
export async function messageRequestAction(id: string, action: "accept" | "reject" | "spam") { const { data } = await api.post<ApiResponse<{ request_id: string; status: string }>>(`/message-requests/${id}/${action}/`, {}, { headers: await authHeader() }); return data; }
export async function deleteMessageRequest(id: string) { const { data } = await api.delete<ApiResponse<Record<string, never>>>(`/message-requests/${id}/delete/`, { headers: await authHeader() }); return data; }
export async function syncConversations(cursor?: string) { const { data } = await api.get<ApiResponse<CursorPage<Conversation>>>("/conversations/sync/", { params: { cursor }, headers: await authHeader() }); return data; }
export async function syncMessages(cursor?: string) { const { data } = await api.get<ApiResponse<CursorPage<ChatMessage>>>("/messages/sync/", { params: { cursor }, headers: await authHeader() }); return data; }
export async function registerDevice(payload: { device_id: string; platform: string; push_token?: string; notification_preferences?: Record<string, unknown> }) { const { data } = await api.post<ApiResponse<{ device_id: string }>>("/devices/", payload, { headers: await authHeader() }); return data; }
