import { api } from "./client";
import { getTokenItem } from "../store/tokenStorage";
import type { ApiResponse } from "../types/auth";
import type { Reel, ReelList, Story, StoryTray } from "../types/phase4";

async function authHeader() { const token = await getTokenItem("manyumbu_access"); return token ? { Authorization: `Bearer ${token}` } : {}; }

export async function getStoryTray() { const { data } = await api.get<ApiResponse<StoryTray>>("/stories/tray/", { headers: await authHeader() }); return data; }
export async function getStory(id: string) { const { data } = await api.get<ApiResponse<{ story: Story }>>(`/stories/${id}/`, { headers: await authHeader() }); return data; }
export async function createStory(payload: { caption: string; audience: string; background_style?: string; link_url?: string; location_name?: string; media?: { uri: string; name: string; type: string }; poll?: { question: string; options: string[] } }, onProgress?: (n: number) => void) { const form = new FormData(); Object.entries(payload).forEach(([key, value]) => { if (key === "media" || value === undefined) return; form.append(key, typeof value === "object" ? JSON.stringify(value) : String(value)); }); if (payload.media) form.append("media", payload.media as unknown as Blob); const { data } = await api.post<ApiResponse<{ story: Story }>>("/stories/", form, { headers: { ...(await authHeader()), "Content-Type": "multipart/form-data" }, onUploadProgress: (event) => event.total && onProgress?.(Math.round((event.loaded / event.total) * 100)) }); return data; }
export async function viewStory(id: string) { const { data } = await api.post<ApiResponse<{ view_count: number }>>(`/stories/${id}/view/`, {}, { headers: await authHeader() }); return data; }
export async function reactStory(id: string, reaction: string) { const { data } = await api.post<ApiResponse<{ reaction: string }>>(`/stories/${id}/react/`, { reaction }, { headers: await authHeader() }); return data; }
export async function replyStory(id: string, text: string) { const { data } = await api.post<ApiResponse<{ reply_id: string }>>(`/stories/${id}/reply/`, { text }, { headers: await authHeader() }); return data; }
export async function voteStoryPoll(id: string, option_id: number) { const { data } = await api.post<ApiResponse<Record<string, unknown>>>(`/stories/${id}/poll-vote/`, { option_id }, { headers: await authHeader() }); return data; }
export async function getHighlights(username: string) { const { data } = await api.get<ApiResponse<Record<string, unknown>>>(`/users/${username}/highlights/`, { headers: await authHeader() }); return data; }

export async function getReelFeed(cursor?: string | null) { const { data } = await api.get<ApiResponse<{ results: Reel[]; next_cursor: string | null }>>("/reels/feed/", { params: { cursor }, headers: await authHeader() }); return data; }
export async function getReel(id: string) { const { data } = await api.get<ApiResponse<{ reel: Reel }>>(`/reels/${id}/`, { headers: await authHeader() }); return data; }
export async function createReel(payload: { caption: string; audience: string; video: { uri: string; name: string; type: string }; cover?: { uri: string; name: string; type: string }; status?: string; duration?: number }, onProgress?: (n: number) => void) { const form = new FormData(); Object.entries(payload).forEach(([key, value]) => { if (["video", "cover"].includes(key) || value === undefined) return; form.append(key, String(value)); }); form.append("video", payload.video as unknown as Blob); if (payload.cover) form.append("cover", payload.cover as unknown as Blob); const { data } = await api.post<ApiResponse<{ reel: Reel }>>("/reels/", form, { headers: { ...(await authHeader()), "Content-Type": "multipart/form-data" }, onUploadProgress: (event) => event.total && onProgress?.(Math.round((event.loaded / event.total) * 100)) }); return data; }
export async function reelAction(id: string, action: string, payload = {}) { const { data } = await api.post<ApiResponse<Record<string, unknown>>>(`/reels/${id}/${action}/`, payload, { headers: await authHeader() }); return data; }
export async function getReelList(path: "saved" | "drafts" | "archived") { const map = { saved: "/me/saved-reels/", drafts: "/me/reel-drafts/", archived: "/me/archived-reels/" }; const { data } = await api.get<ApiResponse<ReelList>>(map[path], { headers: await authHeader() }); return data; }
export async function getUserReels(username: string) { const { data } = await api.get<ApiResponse<ReelList>>(`/users/${username}/reels/`, { headers: await authHeader() }); return data; }
export async function getHashtagReels(hashtag: string) { const { data } = await api.get<ApiResponse<ReelList>>(`/reel-hashtags/${hashtag}/`, { headers: await authHeader() }); return data; }
