import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useRef, useState } from "react";
import { FlatList, Pressable, Text, TextInput, View } from "react-native";
import { getGroup, groupAction, groupMessageAction, listGroupMessages, removeGroupMessageAction, sendGroupTextMessage } from "../../src/api/groups";
import { openGroupSocket, sendGroupSocketEvent } from "../../src/groups/socket";
import { validateGroupMessage } from "../../src/groups/validation";
import { createClientMessageId } from "../../src/messaging/queue";
import type { GroupMessage } from "../../src/types/groups";
import type { ChatEvent } from "../../src/types/messaging";

function Bubble({ message, onReact, onStar, onPin, onDeleteMe, onDeleteAll, onRead }: { message: GroupMessage; onReact: () => void; onStar: () => void; onPin: () => void; onDeleteMe: () => void; onDeleteAll: () => void; onRead: () => void }) {
  const deleted = Boolean(message.deleted_for_everyone_at || message.removed_by_moderator);
  return <View style={{ paddingVertical: 8 }}><View style={{ backgroundColor: message.is_system ? "#FEF3C7" : "#F3F8F5", borderRadius: 8, padding: 12 }}><Text style={{ fontWeight: "900" }}>{message.sender.full_name}{message.is_forwarded ? " · forwarded" : ""}</Text>{message.reply_to ? <Text style={{ color: "#6B7280", borderLeftWidth: 3, borderColor: "#126C57", paddingLeft: 8, marginVertical: 6 }}>{message.reply_to.sender.username}: {message.reply_to.text}</Text> : null}<Text style={{ fontSize: 16, marginTop: 4 }}>{deleted ? "Message removed" : message.text || message.message_type}</Text>{message.attachments.map((item) => <Text key={item.id} style={{ marginTop: 6, color: "#126C57" }}>{item.kind}: {item.file_name}</Text>)}<Text style={{ color: "#6B7280", marginTop: 6 }}>{message.status}{message.is_edited ? " · edited" : ""}{message.read_count ? ` · ${message.read_count} read` : ""}</Text><View style={{ flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 8 }}><Pressable onPress={onReact}><Text>React</Text></Pressable><Pressable onPress={onStar}><Text>{message.viewer_has_starred ? "Unstar" : "Star"}</Text></Pressable><Pressable onPress={onPin}><Text>{message.viewer_has_pinned ? "Unpin" : "Pin"}</Text></Pressable><Pressable onPress={onRead}><Text>Read</Text></Pressable><Pressable onPress={onDeleteMe}><Text>Delete me</Text></Pressable><Pressable onPress={onDeleteAll}><Text style={{ color: "#B91C1C" }}>Delete all</Text></Pressable></View>{message.reactions.length ? <Text style={{ marginTop: 6 }}>{message.reactions.map((r) => r.reaction).join(" ")}</Text> : null}</View></View>;
}

export default function GroupDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const groupId = String(id);
  const client = useQueryClient();
  const [text, setText] = useState("");
  const [connection, setConnection] = useState("connecting");
  const [typing, setTyping] = useState(false);
  const socket = useRef<WebSocket | null>(null);
  const group = useQuery({ queryKey: ["group", groupId], queryFn: () => getGroup(groupId) });
  const messages = useQuery({ queryKey: ["group-messages", groupId], queryFn: () => listGroupMessages(groupId) });
  useEffect(() => { let active = true; openGroupSocket(groupId, (event: ChatEvent) => { if (event.event === "connection.ready") setConnection("connected"); if (event.event === "group.message.created") client.invalidateQueries({ queryKey: ["group-messages", groupId] }); if (event.event === "group.typing.updated") setTyping(Boolean(event.data.active)); }).then((ws) => { if (!active) { ws.close(); return; } socket.current = ws; ws.onopen = () => setConnection("connected"); ws.onclose = () => setConnection("offline"); ws.onerror = () => setConnection("offline"); }); return () => { active = false; socket.current?.close(); }; }, [groupId, client]);
  const send = useMutation({ mutationFn: async () => { const error = validateGroupMessage(text); if (error) throw new Error(error); const clientId = createClientMessageId(); const sent = sendGroupSocketEvent(socket.current, "group.message.send", { text, client_message_id: clientId }, clientId); if (!sent) return sendGroupTextMessage(groupId, text, clientId); return null; }, onSuccess: () => { setText(""); client.invalidateQueries({ queryKey: ["group-messages", groupId] }); client.invalidateQueries({ queryKey: ["groups"] }); } });
  const action = useMutation({ mutationFn: ({ msg, name }: { msg: GroupMessage; name: string }) => { if (name === "react") return groupMessageAction(msg.id, "react", { reaction: "love" }); if (name === "star") return msg.viewer_has_starred ? removeGroupMessageAction(msg.id, "star") : groupMessageAction(msg.id, "star"); if (name === "pin") return msg.viewer_has_pinned ? removeGroupMessageAction(msg.id, "pin") : groupMessageAction(msg.id, "pin"); if (name === "read") return groupMessageAction(msg.id, "read"); if (name === "deleteMe") return removeGroupMessageAction(msg.id, "for-me"); return removeGroupMessageAction(msg.id, "for-everyone"); }, onSuccess: () => client.invalidateQueries({ queryKey: ["group-messages", groupId] }) });
  const item = group.data?.data.group;
  return <View style={{ flex: 1, backgroundColor: "#FFFFFF", paddingTop: 44, paddingHorizontal: 14 }}><View style={{ flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 8 }}><Pressable onPress={() => router.back()}><Text style={{ color: "#126C57", fontWeight: "800" }}>Back</Text></Pressable><View style={{ alignItems: "center" }}><Text style={{ fontWeight: "900", fontSize: 18 }}>{item?.name ?? "Group"}</Text><Text style={{ color: "#6B7280" }}>{connection}{typing ? " · typing" : ""} · {item?.member_count ?? 0} members</Text></View><Pressable onPress={() => router.push({ pathname: "/groups/info", params: { id: groupId } })}><Text style={{ color: "#126C57", fontWeight: "800" }}>Info</Text></Pressable></View><View style={{ flexDirection: "row", gap: 12, marginBottom: 8 }}><Pressable onPress={() => groupAction(groupId, "mute", { hours: 8 })}><Text>Mute</Text></Pressable><Pressable onPress={() => groupAction(groupId, "report", { reason: "other" })}><Text>Report</Text></Pressable><Pressable onPress={() => groupAction(groupId, "clear")}><Text>Clear</Text></Pressable><Pressable onPress={() => router.push({ pathname: "/calls/outgoing", params: { groupId, callType: "group_voice" } })}><Text>Voice call</Text></Pressable><Pressable onPress={() => router.push({ pathname: "/calls/outgoing", params: { groupId, callType: "group_video" } })}><Text>Video call</Text></Pressable></View><FlatList inverted data={[...(messages.data?.data.results ?? [])]} keyExtractor={(msg) => msg.id} renderItem={({ item: msg }) => <Bubble message={msg} onReact={() => action.mutate({ msg, name: "react" })} onStar={() => action.mutate({ msg, name: "star" })} onPin={() => action.mutate({ msg, name: "pin" })} onRead={() => action.mutate({ msg, name: "read" })} onDeleteMe={() => action.mutate({ msg, name: "deleteMe" })} onDeleteAll={() => action.mutate({ msg, name: "deleteAll" })} />} /><View style={{ borderTopWidth: 1, borderColor: "#E5E7EB", paddingVertical: 10 }}><View style={{ flexDirection: "row", gap: 8, alignItems: "flex-end" }}><TextInput value={text} onChangeText={(value) => { setText(value); sendGroupSocketEvent(socket.current, value ? "group.typing.start" : "group.typing.stop"); }} placeholder={item?.viewer_can_send ? "Message group" : "You cannot send messages"} editable={Boolean(item?.viewer_can_send)} multiline style={{ flex: 1, minHeight: 44, maxHeight: 120, borderWidth: 1, borderColor: "#D1D5DB", borderRadius: 8, padding: 10 }} /><Pressable onPress={() => send.mutate()}><Text style={{ color: "#126C57", fontWeight: "900" }}>Send</Text></Pressable></View>{send.isError ? <Text style={{ color: "#B91C1C", marginTop: 6 }}>{send.error.message}</Text> : null}</View></View>;
}
