from django.urls import path

from .phase4_views import (
    AdminStoryReelView,
    HighlightListView,
    HighlightStoryView,
    HighlightView,
    ReelCollectionView,
    ReelCommentsView,
    ReelDetailView,
    ReelFeedView,
    ReelListsView,
    ReelSimpleActionView,
    StoryCollectionView,
    StoryDetailView,
    StoryPollVoteView,
    StoryReactionView,
    StoryReplyView,
    StoryReportView,
    StoryTrayView,
    StoryViewersView,
    StoryViewView,
)
from .post_views import (
    AdminPostManagementView,
    ArchivedPostsView,
    CommentDetailView,
    CommentLikeView,
    FeedView,
    HashtagPostsView,
    PostArchiveView,
    PostCollectionView,
    PostCommentsView,
    PostDetailView,
    PostHideView,
    PostLikeView,
    PostLikesListView,
    PostReportView,
    PostSaveView,
    SavedPostsView,
    UserPostsView,
)
from .profile_views import (
    BlockView,
    CloseFriendsView,
    FollowRequestActionView,
    FollowView,
    MeProfileView,
    MutedView,
    PrivacySettingsView,
    ProfileMediaView,
    PublicProfileView,
    RelationshipListView,
    RemoveFollowerView,
    RestrictedView,
    SearchProfilesView,
)
from .views import (
    ForgotPasswordView,
    GoogleAuthStartView,
    LoginView,
    RegisterView,
    ResendVerificationView,
    ResetPasswordView,
    TokenRefreshView,
    VerifyEmailView,
)

urlpatterns = [
    path("auth/register/", RegisterView.as_view(), name="auth-register"),
    path("auth/verify-email/", VerifyEmailView.as_view(), name="auth-verify-email"),
    path("auth/resend-code/", ResendVerificationView.as_view(), name="auth-resend-code"),
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/token/refresh/", TokenRefreshView.as_view(), name="auth-token-refresh"),
    path("auth/forgot-password/", ForgotPasswordView.as_view(), name="auth-forgot-password"),
    path("auth/reset-password/", ResetPasswordView.as_view(), name="auth-reset-password"),
    path("auth/google/start/", GoogleAuthStartView.as_view(), name="auth-google-start"),
    path("profiles/me/", MeProfileView.as_view(), name="profile-me"),
    path("profiles/me/media/", ProfileMediaView.as_view(), name="profile-media"),
    path("profiles/search/", SearchProfilesView.as_view(), name="profile-search"),
    path("profiles/privacy/", PrivacySettingsView.as_view(), name="profile-privacy"),
    path("profiles/<str:username>/", PublicProfileView.as_view(), name="profile-public"),
    path("profiles/<str:username>/follow/", FollowView.as_view(), name="profile-follow"),
    path("profiles/<str:username>/remove-follower/", RemoveFollowerView.as_view(), name="profile-remove-follower"),
    path("follow-requests/<int:request_id>/<str:action>/", FollowRequestActionView.as_view(), name="follow-request-action"),
    path("relationships/blocked/", BlockView.as_view(), name="blocked-list"),
    path("relationships/blocked/<str:username>/", BlockView.as_view(), name="blocked-action"),
    path("relationships/restricted/", RestrictedView.as_view(), name="restricted-list"),
    path("relationships/restricted/<str:username>/", RestrictedView.as_view(), name="restricted-action"),
    path("relationships/muted/", MutedView.as_view(), name="muted-list"),
    path("relationships/muted/<str:username>/", MutedView.as_view(), name="muted-action"),
    path("relationships/close-friends/", CloseFriendsView.as_view(), name="close-friends-list"),
    path("relationships/close-friends/<str:username>/", CloseFriendsView.as_view(), name="close-friends-action"),
    path("stories/", StoryCollectionView.as_view(), name="story-create"),
    path("stories/tray/", StoryTrayView.as_view(), name="story-tray"),
    path("stories/<uuid:story_id>/", StoryDetailView.as_view(), name="story-detail"),
    path("stories/<uuid:story_id>/view/", StoryViewView.as_view(), name="story-view"),
    path("stories/<uuid:story_id>/viewers/", StoryViewersView.as_view(), name="story-viewers"),
    path("stories/<uuid:story_id>/react/", StoryReactionView.as_view(), name="story-react"),
    path("stories/<uuid:story_id>/reply/", StoryReplyView.as_view(), name="story-reply"),
    path("stories/<uuid:story_id>/report/", StoryReportView.as_view(), name="story-report"),
    path("stories/<uuid:story_id>/poll-vote/", StoryPollVoteView.as_view(), name="story-poll-vote"),
    path("users/<str:username>/highlights/", HighlightListView.as_view(), name="user-highlights"),
    path("highlights/", HighlightView.as_view(), name="highlight-create"),
    path("highlights/<uuid:highlight_id>/", HighlightView.as_view(), name="highlight-detail"),
    path("highlights/<uuid:highlight_id>/stories/", HighlightStoryView.as_view(), name="highlight-add-story"),
    path("highlights/<uuid:highlight_id>/stories/<uuid:story_id>/", HighlightStoryView.as_view(), name="highlight-remove-story"),
    path("reels/", ReelCollectionView.as_view(), name="reel-create"),
    path("reels/feed/", ReelFeedView.as_view(), name="reel-feed"),
    path("reels/<uuid:reel_id>/", ReelDetailView.as_view(), name="reel-detail"),
    path("reels/<uuid:reel_id>/comments/", ReelCommentsView.as_view(), name="reel-comments"),
    path("reels/<uuid:reel_id>/<str:action>/", ReelSimpleActionView.as_view(), name="reel-action"),
    path("me/saved-reels/", ReelListsView.as_view(), {"list_name": "saved"}, name="saved-reels"),
    path("me/reel-drafts/", ReelListsView.as_view(), {"list_name": "drafts"}, name="reel-drafts"),
    path("me/archived-reels/", ReelListsView.as_view(), {"list_name": "archived"}, name="archived-reels"),
    path("users/<str:username>/reels/", ReelListsView.as_view(), name="user-reels"),
    path("reel-hashtags/<str:hashtag>/", ReelListsView.as_view(), name="reel-hashtag"),
    path("admin/posts/", AdminPostManagementView.as_view(), name="admin-posts"),
    path("admin/posts/<uuid:post_id>/", AdminPostManagementView.as_view(), name="admin-post-detail"),
    path("admin/posts/<uuid:post_id>/<str:action>/", AdminPostManagementView.as_view(), name="admin-post-action"),
    path("admin/<str:kind>/", AdminStoryReelView.as_view(), name="admin-story-reel-list"),
    path("admin/<str:kind>/<uuid:item_id>/<str:action>/", AdminStoryReelView.as_view(), name="admin-story-reel-action"),
    path("posts/", PostCollectionView.as_view(), name="post-collection"),
    path("posts/<uuid:post_id>/like/", PostLikeView.as_view(), name="post-like"),
    path("posts/<uuid:post_id>/save/", PostSaveView.as_view(), name="post-save"),
    path("posts/<uuid:post_id>/likes/", PostLikesListView.as_view(), name="post-likes"),
    path("posts/<uuid:post_id>/comments/", PostCommentsView.as_view(), name="post-comments"),
    path("posts/<uuid:post_id>/archive/", PostArchiveView.as_view(), {"action": "archive"}, name="post-archive"),
    path("posts/<uuid:post_id>/restore/", PostArchiveView.as_view(), {"action": "restore"}, name="post-restore"),
    path("posts/<uuid:post_id>/report/", PostReportView.as_view(), name="post-report"),
    path("posts/<uuid:post_id>/hide/", PostHideView.as_view(), name="post-hide"),
    path("posts/<uuid:post_id>/", PostDetailView.as_view(), name="post-detail"),
    path("comments/<uuid:comment_id>/", CommentDetailView.as_view(), name="comment-detail"),
    path("comments/<uuid:comment_id>/like/", CommentLikeView.as_view(), name="comment-like"),
    path("feed/", FeedView.as_view(), name="feed"),
    path("users/<str:username>/posts/", UserPostsView.as_view(), name="user-posts"),
    path("me/saved-posts/", SavedPostsView.as_view(), name="saved-posts"),
    path("me/archived-posts/", ArchivedPostsView.as_view(), name="archived-posts"),
    path("hashtags/<str:hashtag>/posts/", HashtagPostsView.as_view(), name="hashtag-posts"),
    path("relationships/<str:list_name>/", RelationshipListView.as_view(), name="relationship-list"),
]






