from django.urls import path

from .group_views import (
    AdminGroupModerationView,
    GroupDetailView,
    GroupInvitationJoinView,
    GroupInvitationView,
    GroupJoinRequestView,
    GroupListView,
    GroupMembersView,
    GroupMembershipActionView,
    GroupMessageActionView,
    GroupMessagesView,
    GroupSearchMediaView,
    NotificationPreferenceView,
    NotificationView,
)
from .phase7_views import (
    AdminPhaseSevenView,
    AppealView,
    BusinessAccountView,
    CallActionView,
    CallDetailView,
    CallHistoryView,
    CallListView,
    CallPrivacyView,
    CreatorAccountView,
    ModerationActionView,
    ProfessionalAccountView,
    ProfessionalInsightView,
    RestrictionView,
    VerificationRequestView,
)
from .messaging_views import (
    AdminMessageReportView,
    ConversationDetailView,
    ConversationListView,
    ConversationMessagesView,
    ConversationStateView,
    DeviceView,
    MessageActionView,
    MessageDeleteForEveryoneView,
    MessageDeleteForMeView,
    MessageDetailView,
    MessageRequestActionView,
    MessageRequestListView,
    MessageSearchView,
    MessagingSyncView,
    SharedMediaView,
)
from .phase4_views import (
    AdminStoryReelView,
    HighlightListView,
    HighlightStoryView,
    HighlightView,
    ReelCollectionView,
    ReelCommentsView,
    ReelDetailView,
    ReelFeedView,
    ReelListsView,
    ReelSimpleActionView,
    StoryCollectionView,
    StoryDetailView,
    StoryPollVoteView,
    StoryReactionView,
    StoryReplyView,
    StoryReportView,
    StoryTrayView,
    StoryViewersView,
    StoryViewView,
)
from .post_views import (
    AdminPostManagementView,
    ArchivedPostsView,
    CommentDetailView,
    CommentLikeView,
    FeedView,
    HashtagPostsView,
    PostArchiveView,
    PostCollectionView,
    PostCommentsView,
    PostDetailView,
    PostHideView,
    PostLikeView,
    PostLikesListView,
    PostReportView,
    PostSaveView,
    SavedPostsView,
    UserPostsView,
)
from .profile_views import (
    BlockView,
    CloseFriendsView,
    FollowRequestActionView,
    FollowView,
    MeProfileView,
    MutedView,
    PrivacySettingsView,
    ProfileMediaView,
    PublicProfileView,
    RelationshipListView,
    RemoveFollowerView,
    RestrictedView,
    SearchProfilesView,
)
from .views import (
    ForgotPasswordView,
    GoogleAuthStartView,
    LoginView,
    RegisterView,
    ResendVerificationView,
    ResetPasswordView,
    TokenRefreshView,
    VerifyEmailView,
)

urlpatterns = [
    path("auth/register/", RegisterView.as_view(), name="auth-register"),
    path("auth/verify-email/", VerifyEmailView.as_view(), name="auth-verify-email"),
    path("auth/resend-code/", ResendVerificationView.as_view(), name="auth-resend-code"),
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/token/refresh/", TokenRefreshView.as_view(), name="auth-token-refresh"),
    path("auth/forgot-password/", ForgotPasswordView.as_view(), name="auth-forgot-password"),
    path("auth/reset-password/", ResetPasswordView.as_view(), name="auth-reset-password"),
    path("auth/google/start/", GoogleAuthStartView.as_view(), name="auth-google-start"),
    path("profiles/me/", MeProfileView.as_view(), name="profile-me"),
    path("profiles/me/media/", ProfileMediaView.as_view(), name="profile-media"),
    path("profiles/search/", SearchProfilesView.as_view(), name="profile-search"),
    path("profiles/privacy/", PrivacySettingsView.as_view(), name="profile-privacy"),
    path("profiles/<str:username>/", PublicProfileView.as_view(), name="profile-public"),
    path("profiles/<str:username>/follow/", FollowView.as_view(), name="profile-follow"),
    path("profiles/<str:username>/remove-follower/", RemoveFollowerView.as_view(), name="profile-remove-follower"),
    path("follow-requests/<int:request_id>/<str:action>/", FollowRequestActionView.as_view(), name="follow-request-action"),
    path("relationships/blocked/", BlockView.as_view(), name="blocked-list"),
    path("relationships/blocked/<str:username>/", BlockView.as_view(), name="blocked-action"),
    path("relationships/restricted/", RestrictedView.as_view(), name="restricted-list"),
    path("relationships/restricted/<str:username>/", RestrictedView.as_view(), name="restricted-action"),
    path("relationships/muted/", MutedView.as_view(), name="muted-list"),
    path("relationships/muted/<str:username>/", MutedView.as_view(), name="muted-action"),
    path("relationships/close-friends/", CloseFriendsView.as_view(), name="close-friends-list"),
    path("relationships/close-friends/<str:username>/", CloseFriendsView.as_view(), name="close-friends-action"),
    path("calls/", CallListView.as_view(), name="call-list"),
    path("calls/privacy/", CallPrivacyView.as_view(), name="call-privacy"),
    path("calls/<uuid:call_id>/", CallDetailView.as_view(), name="call-detail"),
    path("calls/<uuid:call_id>/history/", CallHistoryView.as_view(), name="call-history-delete"),
    path("calls/<uuid:call_id>/<str:action>/", CallActionView.as_view(), name="call-action"),
    path("professional-account/", ProfessionalAccountView.as_view(), name="professional-account"),
    path("professional-account/creator/", CreatorAccountView.as_view(), name="professional-account-creator"),
    path("professional-account/business/", BusinessAccountView.as_view(), name="professional-account-business"),
    path("professional-account/insights/", ProfessionalInsightView.as_view(), name="professional-account-insights"),
    path("verification-requests/", VerificationRequestView.as_view(), name="verification-requests"),
    path("verification-requests/<uuid:request_id>/", VerificationRequestView.as_view(), name="verification-request-detail"),
    path("moderation/actions/", ModerationActionView.as_view(), name="moderation-actions"),
    path("moderation/restrictions/", RestrictionView.as_view(), name="moderation-restrictions"),
    path("moderation/actions/<uuid:action_id>/appeal/", AppealView.as_view(), name="moderation-action-appeal"),
    path("moderation/appeals/", AppealView.as_view(), name="moderation-appeals"),
    path("admin/moderation/queue/", AdminPhaseSevenView.as_view(), {"kind": "queue"}, name="admin-moderation-queue"),
    path("admin/call-reports/", AdminPhaseSevenView.as_view(), {"kind": "call-reports"}, name="admin-call-reports"),
    path("admin/appeals/", AdminPhaseSevenView.as_view(), {"kind": "appeals"}, name="admin-appeals"),
    path("admin/appeals/<uuid:object_id>/<str:action>/", AdminPhaseSevenView.as_view(), {"kind": "appeals"}, name="admin-appeal-decision"),
    path("admin/verification-requests/", AdminPhaseSevenView.as_view(), {"kind": "verification-requests"}, name="admin-verification-requests"),
    path("admin/verification-requests/<uuid:object_id>/<str:action>/", AdminPhaseSevenView.as_view(), {"kind": "verification-requests"}, name="admin-verification-action"),
    path("admin/professional-accounts/", AdminPhaseSevenView.as_view(), {"kind": "professional-accounts"}, name="admin-professional-accounts"),
    path("admin/professional-accounts/<str:username>/<str:action>/", AdminPhaseSevenView.as_view(), {"kind": "professional-accounts"}, name="admin-professional-action"),
    path("admin/users/<str:username>/restrictions/", AdminPhaseSevenView.as_view(), {"kind": "users", "action": "restrictions"}, name="admin-user-restrictions"),
    path("admin/users/<str:username>/restrictions/<int:object_id>/", AdminPhaseSevenView.as_view(), {"kind": "users"}, name="admin-user-restriction-delete"),    path("groups/", GroupListView.as_view(), name="group-list"),
    path("groups/<uuid:group_id>/", GroupDetailView.as_view(), name="group-detail"),
    path("groups/<uuid:group_id>/members/", GroupMembersView.as_view(), name="group-members"),
    path("groups/<uuid:group_id>/members/<str:user_identifier>/", GroupMembersView.as_view(), name="group-member-detail"),
    path("groups/<uuid:group_id>/messages/", GroupMessagesView.as_view(), name="group-messages"),
    path("groups/<uuid:group_id>/search/", GroupSearchMediaView.as_view(), {"kind": "search"}, name="group-search"),
    path("groups/<uuid:group_id>/media/", GroupSearchMediaView.as_view(), {"kind": "media"}, name="group-media"),
    path("groups/<uuid:group_id>/invitations/", GroupInvitationView.as_view(), name="group-invitations"),
    path("groups/<uuid:group_id>/invitations/<uuid:invitation_id>/", GroupInvitationView.as_view(), name="group-invitation-detail"),
    path("group-invitations/<str:token>/join/", GroupInvitationJoinView.as_view(), name="group-invitation-join"),
    path("groups/<uuid:group_id>/join-requests/", GroupJoinRequestView.as_view(), name="group-join-requests"),
    path("groups/<uuid:group_id>/join-requests/<uuid:request_id>/<str:action>/", GroupJoinRequestView.as_view(), name="group-join-request-action"),
    path("groups/<uuid:group_id>/<str:action>/", GroupMembershipActionView.as_view(), name="group-action"),
    path("group-messages/<uuid:message_id>/", GroupMessageActionView.as_view(), name="group-message-detail"),
    path("group-messages/<uuid:message_id>/<str:action>/", GroupMessageActionView.as_view(), name="group-message-action"),
    path("notifications/", NotificationView.as_view(), name="notifications"),
    path("notifications/read-all/", NotificationView.as_view(), {"action": "read-all"}, name="notifications-read-all"),
    path("notifications/<uuid:notification_id>/<str:action>/", NotificationView.as_view(), name="notification-action"),
    path("notification-preferences/", NotificationPreferenceView.as_view(), name="notification-preferences"),
    path("admin/groups/", AdminGroupModerationView.as_view(), name="admin-groups"),
    path("admin/groups/<uuid:group_id>/<str:action>/", AdminGroupModerationView.as_view(), name="admin-group-action"),
    path("admin/announcements/<str:action>/", AdminGroupModerationView.as_view(), name="admin-announcements"),
    path("conversations/", ConversationListView.as_view(), name="conversation-list"),
    path("conversations/sync/", MessagingSyncView.as_view(), {"kind": "conversations"}, name="conversation-sync"),
    path("conversations/<uuid:conversation_id>/", ConversationDetailView.as_view(), name="conversation-detail"),
    path("conversations/<uuid:conversation_id>/messages/", ConversationMessagesView.as_view(), name="conversation-messages"),
    path("conversations/<uuid:conversation_id>/search/", MessageSearchView.as_view(), name="conversation-message-search"),
    path("conversations/<uuid:conversation_id>/media/", SharedMediaView.as_view(), name="conversation-media"),
    path("conversations/<uuid:conversation_id>/<str:action>/", ConversationStateView.as_view(), name="conversation-state"),
    path("messages/sync/", MessagingSyncView.as_view(), {"kind": "messages"}, name="message-sync"),
    path("messages/<uuid:message_id>/", MessageDetailView.as_view(), name="message-detail"),
    path("messages/<uuid:message_id>/for-me/", MessageDeleteForMeView.as_view(), name="message-delete-for-me"),
    path("messages/<uuid:message_id>/for-everyone/", MessageDeleteForEveryoneView.as_view(), name="message-delete-for-everyone"),
    path("messages/<uuid:message_id>/<str:action>/", MessageActionView.as_view(), name="message-action"),
    path("message-requests/", MessageRequestListView.as_view(), name="message-request-list"),
    path("message-requests/<uuid:request_id>/<str:action>/", MessageRequestActionView.as_view(), name="message-request-action"),
    path("devices/", DeviceView.as_view(), name="user-devices"),
    path("admin/message-reports/", AdminMessageReportView.as_view(), name="admin-message-reports"),
    path("admin/message-reports/<str:report_kind>/<int:report_id>/<str:action>/", AdminMessageReportView.as_view(), name="admin-message-report-action"),
    path("stories/", StoryCollectionView.as_view(), name="story-create"),    path("stories/tray/", StoryTrayView.as_view(), name="story-tray"),
    path("stories/<uuid:story_id>/", StoryDetailView.as_view(), name="story-detail"),
    path("stories/<uuid:story_id>/view/", StoryViewView.as_view(), name="story-view"),
    path("stories/<uuid:story_id>/viewers/", StoryViewersView.as_view(), name="story-viewers"),
    path("stories/<uuid:story_id>/react/", StoryReactionView.as_view(), name="story-react"),
    path("stories/<uuid:story_id>/reply/", StoryReplyView.as_view(), name="story-reply"),
    path("stories/<uuid:story_id>/report/", StoryReportView.as_view(), name="story-report"),
    path("stories/<uuid:story_id>/poll-vote/", StoryPollVoteView.as_view(), name="story-poll-vote"),
    path("users/<str:username>/highlights/", HighlightListView.as_view(), name="user-highlights"),
    path("highlights/", HighlightView.as_view(), name="highlight-create"),
    path("highlights/<uuid:highlight_id>/", HighlightView.as_view(), name="highlight-detail"),
    path("highlights/<uuid:highlight_id>/stories/", HighlightStoryView.as_view(), name="highlight-add-story"),
    path("highlights/<uuid:highlight_id>/stories/<uuid:story_id>/", HighlightStoryView.as_view(), name="highlight-remove-story"),
    path("reels/", ReelCollectionView.as_view(), name="reel-create"),
    path("reels/feed/", ReelFeedView.as_view(), name="reel-feed"),
    path("reels/<uuid:reel_id>/", ReelDetailView.as_view(), name="reel-detail"),
    path("reels/<uuid:reel_id>/comments/", ReelCommentsView.as_view(), name="reel-comments"),
    path("reels/<uuid:reel_id>/<str:action>/", ReelSimpleActionView.as_view(), name="reel-action"),
    path("me/saved-reels/", ReelListsView.as_view(), {"list_name": "saved"}, name="saved-reels"),
    path("me/reel-drafts/", ReelListsView.as_view(), {"list_name": "drafts"}, name="reel-drafts"),
    path("me/archived-reels/", ReelListsView.as_view(), {"list_name": "archived"}, name="archived-reels"),
    path("users/<str:username>/reels/", ReelListsView.as_view(), name="user-reels"),
    path("reel-hashtags/<str:hashtag>/", ReelListsView.as_view(), name="reel-hashtag"),
    path("admin/posts/", AdminPostManagementView.as_view(), name="admin-posts"),
    path("admin/posts/<uuid:post_id>/", AdminPostManagementView.as_view(), name="admin-post-detail"),
    path("admin/posts/<uuid:post_id>/<str:action>/", AdminPostManagementView.as_view(), name="admin-post-action"),
    path("admin/<str:kind>/", AdminStoryReelView.as_view(), name="admin-story-reel-list"),
    path("admin/<str:kind>/<uuid:item_id>/<str:action>/", AdminStoryReelView.as_view(), name="admin-story-reel-action"),
    path("posts/", PostCollectionView.as_view(), name="post-collection"),
    path("posts/<uuid:post_id>/like/", PostLikeView.as_view(), name="post-like"),
    path("posts/<uuid:post_id>/save/", PostSaveView.as_view(), name="post-save"),
    path("posts/<uuid:post_id>/likes/", PostLikesListView.as_view(), name="post-likes"),
    path("posts/<uuid:post_id>/comments/", PostCommentsView.as_view(), name="post-comments"),
    path("posts/<uuid:post_id>/archive/", PostArchiveView.as_view(), {"action": "archive"}, name="post-archive"),
    path("posts/<uuid:post_id>/restore/", PostArchiveView.as_view(), {"action": "restore"}, name="post-restore"),
    path("posts/<uuid:post_id>/report/", PostReportView.as_view(), name="post-report"),
    path("posts/<uuid:post_id>/hide/", PostHideView.as_view(), name="post-hide"),
    path("posts/<uuid:post_id>/", PostDetailView.as_view(), name="post-detail"),
    path("comments/<uuid:comment_id>/", CommentDetailView.as_view(), name="comment-detail"),
    path("comments/<uuid:comment_id>/like/", CommentLikeView.as_view(), name="comment-like"),
    path("feed/", FeedView.as_view(), name="feed"),
    path("users/<str:username>/posts/", UserPostsView.as_view(), name="user-posts"),
    path("me/saved-posts/", SavedPostsView.as_view(), name="saved-posts"),
    path("me/archived-posts/", ArchivedPostsView.as_view(), name="archived-posts"),
    path("hashtags/<str:hashtag>/posts/", HashtagPostsView.as_view(), name="hashtag-posts"),
    path("relationships/<str:list_name>/", RelationshipListView.as_view(), name="relationship-list"),
]
