import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { router } from "expo-router";
import { useState } from "react";
import { FlatList, Pressable, Text, TextInput, View } from "react-native";
import { conversationAction, listConversations } from "../../src/api/messaging";
import type { Conversation } from "../../src/types/messaging";

function Row({ item, onArchive, onUnread }: { item: Conversation; onArchive: () => void; onUnread: () => void }) {
  const preview = item.last_message?.deleted_for_everyone_at ? "Message deleted" : item.last_message?.text || item.last_message?.message_type || "No messages yet";
  return <Pressable onPress={() => router.push({ pathname: "/chats/[id]", params: { id: item.id } })} style={{ paddingVertical: 14, borderBottomWidth: 1, borderColor: "#E5E7EB", flexDirection: "row", gap: 12 }}><View style={{ width: 48, height: 48, borderRadius: 24, backgroundColor: "#126C57", alignItems: "center", justifyContent: "center" }}><Text style={{ color: "white", fontWeight: "800" }}>{item.peer?.username?.[0]?.toUpperCase() ?? "M"}</Text></View><View style={{ flex: 1 }}><View style={{ flexDirection: "row", justifyContent: "space-between" }}><Text style={{ fontWeight: "800", fontSize: 16 }}>{item.peer?.full_name ?? "Conversation"}{item.peer?.is_verified ? " ?" : ""}</Text><Text style={{ color: "#6B7280", fontSize: 12 }}>{item.last_message_at ? new Date(item.last_message_at).toLocaleTimeString() : ""}</Text></View><Text numberOfLines={1} style={{ color: "#4B5563", marginTop: 3 }}>{item.request_state === "pending" ? "Message request" : preview}</Text><View style={{ flexDirection: "row", gap: 8, marginTop: 8 }}><Pressable onPress={onArchive}><Text style={{ color: "#126C57", fontWeight: "700" }}>{item.archived ? "Unarchive" : "Archive"}</Text></Pressable><Pressable onPress={onUnread}><Text style={{ color: "#126C57", fontWeight: "700" }}>Unread</Text></Pressable>{item.muted_until ? <Text style={{ color: "#9CA3AF" }}>Muted</Text> : null}{item.unread_count ? <Text style={{ backgroundColor: "#E11D48", color: "white", paddingHorizontal: 8, borderRadius: 10 }}>{item.unread_count}</Text> : null}</View></View></Pressable>;
}

export default function ChatsScreen() {
  const [q, setQ] = useState("");
  const [archived, setArchived] = useState(false);
  const client = useQueryClient();
  const query = useQuery({ queryKey: ["conversations", q, archived], queryFn: () => listConversations({ q, archived }) });
  const action = useMutation({ mutationFn: ({ id, name }: { id: string; name: "archive" | "unarchive" | "unread" }) => conversationAction(id, name), onSuccess: () => client.invalidateQueries({ queryKey: ["conversations"] }) });
  return <View style={{ flex: 1, backgroundColor: "#FFFFFF", paddingTop: 48, paddingHorizontal: 18 }}><View style={{ flexDirection: "row", justifyContent: "space-between", alignItems: "center" }}><Text style={{ fontSize: 28, fontWeight: "900" }}>Chats</Text><Pressable onPress={() => router.push("/chats/start")}><Text style={{ color: "#126C57", fontWeight: "900" }}>New</Text></Pressable></View><View style={{ flexDirection: "row", gap: 10, marginVertical: 12 }}><TextInput value={q} onChangeText={setQ} placeholder="Search conversations" style={{ flex: 1, borderWidth: 1, borderColor: "#D1D5DB", borderRadius: 8, padding: 12 }} /><Pressable onPress={() => setArchived(!archived)} style={{ justifyContent: "center" }}><Text style={{ color: "#126C57", fontWeight: "800" }}>{archived ? "Inbox" : "Archived"}</Text></Pressable></View><Pressable onPress={() => router.push("/chats/requests")}><Text style={{ color: "#126C57", fontWeight: "800", marginBottom: 8 }}>Message requests</Text></Pressable>{query.isLoading ? <Text>Loading conversations...</Text> : null}{query.isError ? <Text>Conversations could not be loaded.</Text> : null}<FlatList data={query.data?.data.results ?? []} keyExtractor={(item) => item.id} refreshing={query.isFetching} onRefresh={() => query.refetch()} ListEmptyComponent={<Text style={{ color: "#6B7280", marginTop: 24 }}>No conversations yet.</Text>} renderItem={({ item }) => <Row item={item} onArchive={() => action.mutate({ id: item.id, name: item.archived ? "unarchive" : "archive" })} onUnread={() => action.mutate({ id: item.id, name: "unread" })} />} /></View>;
}
